In [1]:
import numpy as np

energy_consumption = np.random.uniform(1.5, 5.0, 24)
print("Energy Consumption Data (24 hours):\n", energy_consumption)

Energy Consumption Data (24 hours):
 [3.50420069 3.07106822 2.96110312 2.27799059 3.82199038 3.69238177
 4.91522581 4.83682984 3.7467373  3.39342151 3.80585392 3.81674801
 4.20078497 2.6422863  3.7902797  2.18102506 2.76612903 3.87099162
 3.32234034 2.08835553 4.45622675 3.38909851 4.31145794 2.83951727]


In [2]:
average_consumption = np.mean(energy_consumption)
print(f"\nAverage Energy Consumption: {average_consumption:.2f} kWh")

max_consumption = np.max(energy_consumption)
min_consumption = np.min(energy_consumption)
print(f"Maximum Energy Consumption: {max_consumption:.2f} kWh")
print(f"Minimum Energy Consumption: {min_consumption:.2f} kWh")

hour_3_consumption = energy_consumption[2]
print(f"\nEnergy consumption at hour 3: {hour_3_consumption:.2f} kWh")

sorted_consumption = np.sort(energy_consumption)
print("\nSorted Energy Consumption:\n", sorted_consumption)

high_usage = energy_consumption[energy_consumption > 3.0]
print("\nEnergy usage greater than 3.0 kWh:\n", high_usage)

specific_range_count = np.sum((energy_consumption >= 2.5) & (energy_consumption <= 4.0))
print(f"\nNumber of hours with consumption between 2.5 and 4.0 kWh: {specific_range_count}")

reshaped_consumption = energy_consumption.reshape(6, 4)
print("\nReshaped 6x4 Energy Consumption Array:\n", reshaped_consumption)

row_sums = np.sum(reshaped_consumption, axis=1)
column_sums = np.sum(reshaped_consumption, axis=0)
print("\nRow-wise sums:\n", row_sums)
print("Column-wise sums:\n", column_sums)


Average Energy Consumption: 3.49 kWh
Maximum Energy Consumption: 4.92 kWh
Minimum Energy Consumption: 2.09 kWh

Energy consumption at hour 3: 2.96 kWh

Sorted Energy Consumption:
 [2.08835553 2.18102506 2.27799059 2.6422863  2.76612903 2.83951727
 2.96110312 3.07106822 3.32234034 3.38909851 3.39342151 3.50420069
 3.69238177 3.7467373  3.7902797  3.80585392 3.81674801 3.82199038
 3.87099162 4.20078497 4.31145794 4.45622675 4.83682984 4.91522581]

Energy usage greater than 3.0 kWh:
 [3.50420069 3.07106822 3.82199038 3.69238177 4.91522581 4.83682984
 3.7467373  3.39342151 3.80585392 3.81674801 4.20078497 3.7902797
 3.87099162 3.32234034 4.45622675 3.38909851 4.31145794]

Number of hours with consumption between 2.5 and 4.0 kWh: 16

Reshaped 6x4 Energy Consumption Array:
 [[3.50420069 3.07106822 2.96110312 2.27799059]
 [3.82199038 3.69238177 4.91522581 4.83682984]
 [3.7467373  3.39342151 3.80585392 3.81674801]
 [4.20078497 2.6422863  3.7902797  2.18102506]
 [2.76612903 3.87099162 3.322340

In [3]:
import pandas as pd

student_names = ['Alice', 'Bob', 'Charlie', 'David']
roll_numbers = [101, 102, 103, 104]

student_series = pd.Series(student_names, index=roll_numbers)
print("\nStudent Names with Roll Numbers:\n", student_series)


Student Names with Roll Numbers:
 101      Alice
102        Bob
103    Charlie
104      David
dtype: object


In [4]:
import pandas as pd

names = ['Alice', 'Bob', 'Charlie', 'David', 'Eve']
ages = [20, 21, 20, 22, 21]
departments = ['CSE', 'ECE', 'CSE', 'MECH', 'ECE']

student_data = {'Name': names, 'Age': ages, 'Department': departments}

student_df = pd.DataFrame(student_data)
print("\nAll Student Records:\n", student_df)

cse_students = student_df[student_df['Department'] == 'CSE']
print("\nRecords of Students in CSE Department:\n", cse_students)


All Student Records:
       Name  Age Department
0    Alice   20        CSE
1      Bob   21        ECE
2  Charlie   20        CSE
3    David   22       MECH
4      Eve   21        ECE

Records of Students in CSE Department:
       Name  Age Department
0    Alice   20        CSE
2  Charlie   20        CSE


In [5]:
import pandas as pd

employee_data = {
    'Name': ['John', 'Jane', 'Peter', 'Susan'],
    'Salary': [60000, 45000, 75000, 48000],
    'Years of Experience': [5, 2, 8, 3]
}

employee_df = pd.DataFrame(employee_data)
print("\nAll Employee Records:\n", employee_df)

high_salary_employees = employee_df[employee_df['Salary'] > 50000]
print("\nEmployees with Salary > 50000:\n", high_salary_employees)


All Employee Records:
     Name  Salary  Years of Experience
0   John   60000                    5
1   Jane   45000                    2
2  Peter   75000                    8
3  Susan   48000                    3

Employees with Salary > 50000:
     Name  Salary  Years of Experience
0   John   60000                    5
2  Peter   75000                    8
